In [6]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [7]:
data = pd.read_csv('Data/mobile.csv')
data.head(2)

X = data.drop(columns = "price_range")
y = data["price_range"].to_numpy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 123)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [16]:
random_forest = RandomForestClassifier()
random_forest.fit(X_train_scaled, y_train) # Fit the classifier on the scaled training data
y_pred = random_forest.predict(X_test_scaled) # Predicted the labels for the scaled test data
print("Accuracy:", accuracy_score(y_test, y_pred)) # Calculate the accuracy of the model on the test data
print('Confusion Matrix: ')
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.88
Confusion Matrix: 
[[116   3   0   0]
 [ 11 106  11   0]
 [  0  15 111  11]
 [  0   0   9 107]]
